apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-master
  labels:
    app: opensearch
    role: master
spec:
  replicas: 1
  serviceName: opensearch-master
  selector:
    matchLabels:
      app: opensearch
      role: master
  template:
    metadata:
      labels:
        app: opensearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:latest
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
        - name: opensearch-master
          image: opensearchproject/opensearch:1.3.3
          imagePullPolicy: IfNotPresent
          env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPENSEARCH_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: bootstrap.memory_lock
            value: "false"
          - name: DISABLE_INSTALL_DEMO_CONFIG
            value: "true"
          - name: DISABLE_SECURITY_PLUGIN
            value: "false"
          - name: cluster.initial_master_nodes
            value: opensearch-master-0
          - name: cluster.name
            value: opensearch-cluster
          - name: discovery.seed_hosts
            value: opensearch
            #- name: node.data
            #value: "false"
            #- name: node.master
            #value: "true"
          - name: node.roles
            value: "master"
          ports:
            - containerPort: 9300
              name: transport
            - containerPort: 9200
              name: http
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
            - name: config
              mountPath: /usr/share/opensearch/config/opensearch.yml
              subPath: opensearch.yml
            - name: ca-cert
              mountPath: /usr/share/opensearch/config/certificates/ca
              readOnly: true
            - name: opensearch-cert
              mountPath: /usr/share/opensearch/config/certificates/opensearch
              readOnly: true
            - name: admin-cert
              mountPath: /usr/share/opensearch/config/certificates/admin
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: opensearch-config
        - name: ca-cert
          secret:
            secretName: ca-cert
        - name: opensearch-cert
          secret:
            secretName: opensearch-cert
        - name: admin-cert
          secret:
            secretName: admin-cert
  volumeClaimTemplates:
  - metadata:
      name: opensearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
