apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  clusterIP: None
  selector:
    app: opensearch
    role: master
  ports:
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
